# Site settings
title: Jacob Jensen's Portfolio
email: jacobjensenCG@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Kibby's website UWU"
keywords: "gamer, gamer, gamer gamer gamer"
skills: "Computer Graphics Engineer - Video Game Designer"
meta_author: Jacob Jensen

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
#disqus_shortname: myshortname
# Footer settings
footer:
  copyright: Jacob Jensen
  social: Around the Web
  credits: Credits
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ff4d4d #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 791013 #FD6E8A
  secondary-dark: 233140 #A2122F



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/JKibbyJ
  - title: github
    url: https://github.com/Pikby


# Credits content
credits: 'The intial template for the website <a href="http://startbootstrap.com">Start Bootstrap</a>. all modifications are done myself '

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
